language: go

go: 
 - "1.10.x"
 - "1.11.x"

env:
 - GO111MODULE=on

matrix:
  include:
  - go: "1.10.x"
    script: go test -cover -race -v ./...
  - go: "1.11.x"
    script: go test -cover -race -v -mod=vendor ./...

install: true